### ISSUE TITLE
WordPress VIP Issue #1

### ISSUE THREAD

**Issue by bearded-avenger** [bearded-avenger/aesop-core#221]
Before we send this for approval there are a few things we need to take care of:

Switch to blog is prohibited, but we're using this to set a transient for the welcome page. Alternative ideas?

https://vip.wordpress.com/documentation/code-review-what-we-look-for/#switch_to_blog
https://github.com/bearded-avenger/aesop-core/blob/release/1.5.1/public/class-aesop-core.php#L233

**Comment by michaelbeil** [comment]
What if we made a call to a modal with an overview of ASE similar to Lasso?

**Comment by harvitronix** [comment]
May be able to safely ignore this issue as well, and instead notify the user on the plugin page (on VIP) to visit the main settings page after activating? Or add to documentation elsewhere... 

Since VIP customers are enterprise-level power users, you may have to hold a few less hands in guiding people to the right place after enabling.

**Comment by bearded-avenger** [comment]
Fix in vip branch. The welcome screen instructs the user to adda code snippet to enable extended style support, but I went ahead and put it in core. So it'll automagically work great now.
